### ISSUE TITLE
WindowsError: [Error -2146893795] (WinXP)

### ISSUE THREAD

**Issue by reingart** [SistemasAgiles/pyfactura#3]
Al ejecutar el último release 0.9d en Windows XP SP3:

```
Traceback (most recent call last):
  File "factura.pyw", line 25, in <module>
  File "pyafipws\padron.pyc", line 28, in <module>
  File "urllib2.pyc", line 94, in <module>
  File "httplib.pyc", line 80, in <module>
  File "mimetools.pyc", line 6, in <module>
  File "tempfile.pyc", line 35, in <module>
  File "random.pyc", line 885, in <module>
  File "random.pyc", line 97, in __init__
    so it is better to simply reseed.
  File "random.pyc", line 113, in seed
    This fixes the problem with randint() which includes the
WindowsError: [Error -2146893795] La DLL proveedora no se ha podido inicializar correctamente
```

**Comment by reingart** [comment]
Incidencia similar en otro proyecto python:

https://github.com/aws/aws-cli/issues/1226

Solución tentativa: remover crypto32.dll del instalador:

https://github.com/aws/aws-cli/commit/9997f6bbaaee01f584a49514dbefe5d5069b9446
